[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", branch="main" }
{{project-name}}-common = { path = "../{{project-name}}-common", features=["userspace"] }
anyhow = "1.0.42"
ctrlc = "3.2"
{% if program_type == "uprobe" %}libc = "0.2.102"{% endif %}
structopt = { version = "0.3"}

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"
