name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        program:
          - kprobe
          - kretprobe
          - fentry
          - fexit
          - uprobe
          - uretprobe
          - sock_ops
          - socket_filter
          - sk_msg
          - xdp
          - classifier
          - cgroup_skb
          - cgroup_sysctl
          - cgroup_sockopt
          - tracepoint
          - lsm
          - tp_btf
          - raw_tracepoint

    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install latest nightly (pinned to nightly-2023-01-10, https://github.com/aya-rs/aya/issues/490)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-10
          components: rust-src

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - name: Install Cargo Generate
        run: cargo install --git https://github.com/cargo-generate/cargo-generate cargo-generate

      - name: Run tests
        run: ./test.sh ${{ github.workspace }} ${{ matrix.program }}
